Turn RootPtr to NonZero
adevore/rudy pull request #10
Opened 2017-07-08 19:26 UTC by WaDelma

This PR turns `RootPtr` to `NonZero` by [abusing](https://github.com/rust-lang/rust/issues/27730#issuecomment-311919692) `&'static ()`.

2017-07-08 20:17 UTC, adevore commented
Thanks! This is a great workaround. It needs two tweaks before merging. An empty RootPtr will be 0, violating the nonzero invariant. To avoid this, the type codes can be shifted up by one. I recommend also introducing a const for the empty type code. Additionally, there should be a debug_assert!() in NonZeroUsize::new() to check the invariant when testing.

2017-07-12 16:24 UTC, adevore requested changes

2017-07-12 16:24 UTC, adevore commented on src/rudymap/rootptr.rs
> +                              "Encoded root ptr was a zero");
I'd like to have lines 62 and 63 in NonZeroUsize::new instead to keep the assertion bundled as close to the invariant as possible. Otherwise, looks good.

2017-07-12 16:26 UTC, adevore commented
Sorry about the delay in review, I'm still learning how to use GitHub's review feature. After the requested tweak, I'll approve. Thanks!

2017-07-12 16:33 UTC, WaDelma commented
Np. I have no clue why I put the assert there when it would obviously fit better in the constructor.

2017-07-12 16:36 UTC, adevore approved these changes

2017-07-12 16:36 UTC, merged